### Nama : Niken Maharani Permata
### NIM    : 2131710006
### Kelas / No abs : MI1F / 19

## JOBSHEET 5

## PEMILIHAN 1

### Tujuan

Mahasiswa mampu menyelesaikan permasalahan/studi kasus menggunakan sintaks pemilihan 1 dan mengimplemantasikannya dalam bahasa pemrogaman java.

### Alat dan Bahan
+ PC/laptop
+ Browser(chrome, firefox, safari)
+ Koneksi internet

### Praktikum

#### Percobaan 1 : Penggunaan if

#### Waktu percobaan : 40 menit

1. Perhatikan flowchart dibawah ini!

    <p align="left">
    <img width="351" height="460" src="images/01.png">
    </p>
    

> Flowchart diatas digunakan untuk menentukan bilangan ganjil/genap, selanjutnya kita akan membuat programnya berdasarkan
> flowchart di atas!

2. Tambahkan library Scanner, deklarasi Scanner, dan buat variabel bil untuk menampung data yang diinput melalui keyboard

    ![](images/03.png)

In [1]:
// Ketik kode program di atas di bawah sini
import java.util.Scanner;
Scanner input = new Scanner(System.in);
int bil;
System.out.print("Masukkan sebuah bilangan: ");
bil = input.nextInt();

Masukkan sebuah bilangan: 27


3. Buatlah struktur kondisi untuk mengecek apakah bilangan tersebut merupakan bilangan genap atau ganjil

    ![](images/04.png)

In [5]:
// Ketik kode program di atas di bawah sini
if(bil%2 == 0){
    System.out.println("Bilangan Genap");
}else{
    System.out.println("Bilangan Ganjil");
}

Bilangan Ganjil


##### Pertanyaan
1. Modifikasi program diatas dibagian struktur pemilihannya sehingga menjadi sebagai berikut:

    ![](images/05.png)

In [6]:
// Ketik kode program di atas di bawah sini
String output = (bil %2 ==0) ? "Bilangan Genap" : "Bilangan Ganjil";
System.out.println(output);

Bilangan Ganjil


2. Jalankan dan amatilah hasilnya!
3. Jelaskan mengapa output program yang dimodifikasi sama dengan output program sebelum dimodifikasi!

#### Percobaan 2 : Penggunaan if else

#### Waktu percobaan : 40 menit

#### Jawaban No 2
Output yang dihasilkan ialah tulisan "Bilangan Ganjil". 

#### Jawaban No 3
Karena output sebelum modifikasi dan setelah modifikasi pada dasarnya sama-sama menggunakan sintaks pemilihan dengan 2 kondisi. Pada output sebelum modifikasi, menggunakan sintaks pemilihan if else, sedangkan pada output setelah modifikasi menggunakan operator ternary. Perbedaannya hanya pada langkah operator ternary lebih ringkas, namun hasil pengolahan sama.

+ Buatlah sebuah variabel nilai untuk menyimpan inputan dari keyboard

    ![](images/06.png)

In [4]:
// Ketik kode program di atas di bawah sini
int nilai;
System.out.print("Masukkan sebuah bilangan: ");
nilai = input.nextInt();

Masukkan sebuah bilangan: 78


+ Tambahkan sebuah kondisi untuk mengecek input pada variabel nilai

    ![](images/07.png)

In [5]:
// Ketik kode program di atas di bawah sini
if(nilai >= 100){
    nilai +=10;
}else{
    nilai -= 10;
}
System.out.println("Hasil akhir nilai adalah " +nilai);

Hasil akhir nilai adalah 68


+ Jalankan program. Amati apa yang terjadi!

##### Pertanyaan
1. Jelaskan fungsi kode program berikut:
    
    ```
    nilai+=10;
    nilai-=10;
    ```

2. Modifikasilah program diatas dimana inputannya yang awalnya hanya satu kemudian diganti 2 inputan (misal : nilai1 dan nilai2), lakukan perhitungan rata-rata kedua nilai tersebut jika nilainya lebih dari sama dengan 100 maka dikurangi 5, sedangkan jika nilai rata-rata tersebut kurang dari 100 maka akan langsung dicetak!

#### Jawaban No 1
Kode program nilai+=10 merupakan contoh pengaplikasian dari operator assignment. Dengan demikian, fungsi dari kode program tersebut ialah untuk memberikan sebuah nilai pada suatu variabel. Dari percobaan diatas, maksud dari kode program yang diinputkan bertujuan untuk memberi tambahan nilai 10 pada variabel, atau mengurangi 10 nilai dari sebuah variabel.

#### Jawaban No 2

In [15]:
import java.util.Scanner;
Scanner input = new Scanner(System.in);
int nilai1, nilai2, rerata, nilaiAkhir;
System.out.print("Masukkan nilai 1: ");
nilai1 = input.nextInt();
System.out.print("Masukkan nilai 2: ");
nilai2 = input.nextInt();
rerata= (nilai1 + nilai2) / 2;
System.out.println("Rata - Rata: " +rerata);
nilaiAkhir = rerata - 5;

if(rerata >= 100){
System.out.println("Hasil akhir nilai adalah " +nilaiAkhir);  
}else
System.out.print("Hasil akhir nilai adalah " +rerata);

Masukkan nilai 1: 356
Masukkan nilai 2: 700
Rata - Rata: 528
Hasil akhir nilai adalah 523


#### Percobaan 3 : Penggunaan if else-if else

#### Waktu percobaan : 40 menit

+ Tambahakan library `Scanner`
+ Buatlah deklarasi `Scanner`
+ Buat variabel umur bertipe `int`

    ![](images/08.png)

In [19]:
// Ketik kode program di atas di bawah sini
int umur;
System.out.print("Masukkan umur Anda: ");
umur = input.nextInt();

Masukkan umur Anda: 19


+ Kode untuk melakukan pengecekan variabel `umur`

    ![](images/09.png)

In [20]:
// Ketik kode program di atas di bawah sini
if(umur > 60)
    System.out.println("Lansia");
else if(umur > 45)
    System.out.println("Tua");
else if(umur > 17)
    System.out.println("Dewasa");
else if(umur > 5)
    System.out.println("Anak-anak");
else
    System.out.println("Balita");

Dewasa


+ Jalankan program dan amati apa yang terjadi!

#### Jawaban
Yang terjadi ialah output yang dihasilkan berupa tulisan "Dewasa". Sebab, variabel yang kita masukkan (19) merupakan variabel angka yang lebih besar dari 17 dan kurang dari 45. Makadari itu, output yang dihasilkan berupa tulisan dalam kategori "Dewasa"

##### Percobaan 4 : Penggunaan switch-case

#### Waktu percobaan : 40 menit

1. Deklarasikan Scanner
1. Buatlah variabel-variabel berikut

    ![](images/10.png)

In [1]:
// Ketik kode program di atas di bawah sini
Scanner sc = new Scanner(System.in);
double angka1, angka2, hasil;
char operator;

3. Kode program untuk meminta inputan dari keyboard

    ![](images/11.png)

In [2]:
// Ketik kode program di atas di bawah sini
System.out.print("Masukkan angka pertama: ");
angka1 = sc.nextDouble();
System.out.print("Masukkan angka kedua: ");
angka2 = sc.nextDouble();
System.out.print("Masukkan operator (+ - * /): ");
operator = sc.next().charAt(0);

Masukkan angka pertama: 27
Masukkan angka kedua: 81
Masukkan operator (+ - * /): -


4. Kode di bawah ini untuk melakukan pengecekan operator yang digunakan sebelum dilakukan operasi aritmatika

    ![](images/12.png)

In [3]:
// Ketik kode program di atas di bawah sini
switch(operator){
    case '+' :
    hasil = angka1 + angka2;
    System.out.println(angka1 + "+" + angka2 + "=" + hasil);
    break;
    case '-':
    hasil = angka1 - angka2;
    System.out.println(angka1 + " - " + angka2 + " = " + hasil);
    break;
    case '*':
    hasil = angka1 - angka2;
    System.out.println(angka1 + " * " + angka2 + " = " + hasil);
    break;
    case '/':
    hasil = angka1 - angka2;
    System.out.println(angka1 + " / " + angka2 + " = " + hasil);
    break;
    default:
    System.out.println("Operator yang Anda masukkan salah");
}

27.0 - 81.0 = -54.0


5. Jalankan program. Amati apa yang terjadi!

### Jawaban No 5
Yang terjadi ialah muncul hasil output operasi aritmatika 27.0 - 81.0 yang memiliki nilai akhir -54.0

##### Pertanyaan
1. Jelaskan fungsi dari break dan default pada percobaan 4 diatas!
2. Jelaskan fungsi perintah kode program dibawah ini pada percobaan 4!

    ```
    operator = sc.next().chartAt(0);
    ```

#### Jawaban No 1
Dari percobaan diatas, dapat disimpulkan bahwa fungsi break artinya berhenti. Berfungsi untuk memerintahkan komputer untuk berhenti mengecek case yang lainnya.
Sedangkan default memiliki fungsi untuk mengerjakan kode dari nilai variabel yang tidak ada sama sekalipun dengan pilihan case di atasnya.

#### Jawaban No 2
Fungsi perintah tersebut ialah untuk menginput karakter dari user dengan type data berupa char

### Tugas

#### Waktu pengerjaan Tugas: 140 menit

1. Buatlah program untuk menginputkan dua buah bilangan bulat, kemudian mencetak salah satu bilangan yang nilainya terbesar.
2. Perhatikan flowchart berikut ini:

![](images/02.png)

> Buatlah program sesuai dengan flowchart diatas!

3. Pada akhir semester seorang dosen menghitung nilai akhir dari mahasiswa yang terdiri dari nilai uas, uts, kuis, dan tugas. Nilai akhir didapatkan dari 40% nilai uas, 30% nilai uts, 10% nilai kuis, dan 20% nilai tugas. Jika nilai akhir dari mahasiswa dibawah 65 maka mahasiswa tersebut akan mendapatkan remidi. Buatlah program untuk membantu mengetahui mahasiswa yang mendapatkan remidi berdasarkan nilai akhir yang didapatkannya!

4. Sebuah toko memberikan diskon kepada pelanggannya dengan ketentuan sebagai berikut:

| Total Belanja     | Potongan |
|-------------------|----------|
| >Rp. 200.000,00   | 2%       |
| >Rp. 500.000,00   | 5%       |
| >Rp. 1.000.000,00 | 10%      |

> Total belanja diperoleh dari pembelian tiga barang yaitu barang A, barang B, dan barang C. Ketika menginputkan harga barang juga menginputkan jumlah barang yang dibeli.

Contoh outputnya
```
Masukkan harga barang A   :100000
Masukkan jumlah barang A  :10
Masukkan harga barang B   :250000
Masukkan jumlah barang B  :5
Masukkan harga barang C   :150000
Masukkan jumlah barang C  :1
---------------------------------------------
                Struk total
---------------------------------------------
Nama Barang 	| 	Harga 	| 	Jumlah 	| 	Total
Barang A            100000         10        1000000   
Barang B            250000         5         1250000   
Barang C            150000         1         150000    
Total       :2400000
Diskon      :240000.0
Total Bayar :2160000.0
```

### Jawaban No 1

In [2]:
import java.util.Scanner;
Scanner input = new Scanner(System.in);
int bilBulat1, bilBulat2, bilBulatBesar;

System.out.print("Masukkan bilangan bulat pertama = ");
bilBulat1 = input.nextInt();
System.out.print("Masukkan bilangan bulat kedua = ");
bilBulat2 = input.nextInt();

if(bilBulat1>bilBulat2) {
    System.out.println("Bilangan terbesar = " +bilBulat1);
}else
System.out.println("Bilangan terbesar = " +bilBulat2)

Masukkan bilangan bulat pertama = 24
Masukkan bilangan bulat kedua = 48
Bilangan terbesar = 48


### Jawaban No 2

In [14]:
import java.util.Scanner;
Scanner input = new Scanner(System.in);
int umur;

System.out.print("Masukkan umur = ");
umur = input.nextInt();

if(umur >= 17){
    System.out.println("Boleh berkendara");
}else{
    System.out.println("Tidak boleh berkendara");
}

Masukkan umur = 19
Boleh berkendara


### Jawaban No 3

In [17]:
import java.util.Scanner;
Scanner input = new Scanner(System.in);
double uas, uts, kuis, tugas, nilaiAkhir, a1, b1, c1, d1;

System.out.print("Masukkan nilai UAS = ");
uas = input.nextDouble();
System.out.print("Masukkan nilai UTS = ");
uts = input.nextDouble();
System.out.print("Masukkan nilai Kuis = ");
kuis = input.nextDouble();
System.out.print("Masukkan nilai Tugas = ");
tugas = input.nextDouble();

//permisalan
//a1 = nilai akhir UAS
//b1 = nilai akhir UTS
//c1 = nilai akhir Kuis
//d1 = nilai akhir Tugas

a1 = 0.40*uas;
b1 = 0.30*uts;
c1 = 0.20*kuis;
d1 = 0.10*tugas;
nilaiAkhir = a1+b1+c1+d1;
System.out.print("Nilai Akhir Mahasiswa= " +nilaiAkhir);

if(nilaiAkhir > 65){
    System.out.print("\nMahasiswa dinyatakan Lulus");
}else{
    System.out.println("Mahasiswa dinyatakan Tidak Lulus");
}

Masukkan nilai UAS = 87
Masukkan nilai UTS = 89
Masukkan nilai Kuis = 85
Masukkan nilai Tugas = 92
Nilai Akhir Mahasiswa= 87.7
Mahasiswa dinyatakan Lulus

### Jawaban No 4

In [18]:
import java.util.Scanner;
Scanner input = new Scanner(System.in);
int a, a1, b, b1, c, c1, tP1, tP2, tP3, totalPembelianAkhir;
double diskon, totalBayar;

//permisalan
//a = harga barang A , a1 = jumlah barang A
//b = harga barang B , b1 = jumlah barang B
//c = harga barang C , c1 = jumlah barang C
//tP1 = total pembelian A
//tP2 = total pembelian B
//tP3 = total pembelian C

System.out.print("Masukkan harga barang A  = ");
a = input.nextInt();
System.out.print("Masukkan jumlah barang A = ");
a1 = input.nextInt();
System.out.print("Masukkan harga barang B  = ");
b = input.nextInt();
System.out.print("Masukkan jumlah barang B = ");
b1 = input.nextInt();
System.out.print("Masukkan harga barang C  = ");
c = input.nextInt();
System.out.print("Masukkan jumlah barang C = ");
c1 = input.nextInt();

tP1 = a1*a;
tP2 = b1*b;
tP3 = c1*c;
totalPembelian = tP1+tP2+tP3;
System.out.println("-----------------------------------------------------------------------");
System.out.println("                              Struk Total                              ");
System.out.println("-----------------------------------------------------------------------");
System.out.println("    Nama Barang      |     Harga     |     Jumlah     |     Total    ");
System.out.println(String.format("Barang A                %s                %s             %s ", a, a1, tP1));
System.out.println(String.format("Barang B                %s                %s             %s ", b, b1, tP2));
System.out.println(String.format("Barang C                %s                %s             %s ", c, c1, tP3));

System.out.println("Total          = " +totalPembelian);

if (totalPembelian > 200000){
diskon = 0.2*totalPembelian;
System.out.println("Diskon         = " +diskon);
}else if (totalPembelian > 500000){
diskon = 0.5*totalPembelian;
System.out.println("Diskon         = " +diskon);
}else if (totalPembelian > 1000000){
diskon = 0.1*totalPembelian;
System.out.println("Diskon         = " +diskon);
}else 
System.out.println("Anda tidak mendapatkan diskon");

totalBayar = totalPembelian-diskon;
System.out.println("Total Bayar    = " +totalBayar);

Masukkan harga barang A  = 299000
Masukkan jumlah barang A = 2
Masukkan harga barang B  = 76000
Masukkan jumlah barang B = 4
Masukkan harga barang C  = 25900
Masukkan jumlah barang C = 3
-----------------------------------------------------------------------
                              Struk Total                              
-----------------------------------------------------------------------
    Nama Barang      |     Harga     |     Jumlah     |     Total    
Barang A                299000                2             598000 
Barang B                76000                4             304000 
Barang C                25900                3             77700 
Total          = 979700
Diskon         = 195940.0
Total Bayar    = 783760.0
